# Generated by Django 3.2.25 on 2024-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_number',
            field=models.IntegerField(null=True, verbose_name='Codigo Postal'),
        ),
    ]
