# Generated by Django 3.2.25 on 2024-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20240605_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area_number',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
