# Generated by Django 3.2.25 on 2024-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20240605_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_number',
            field=models.IntegerField(verbose_name='Codigo Postal'),
        ),
    ]
