# Generated by Django 3.2.25 on 2024-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen1', models.ImageField(upload_to='productos')),
                ('imagen2', models.ImageField(upload_to='productos')),
                ('imagen3', models.ImageField(blank=True, upload_to='productos')),
                ('imagen4', models.ImageField(blank=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('producto', models.ManyToManyField(to='productos.Producto')),
            ],
        ),
    ]
