# Generated by Django 3.2.25 on 2024-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen1', models.ImageField(upload_to='productos')),
                ('imagen2', models.ImageField(upload_to='productos')),
                ('imagen3', models.ImageField(upload_to='productos')),
                ('imagen4', models.ImageField(upload_to='productos')),
            ],
        ),
    ]
