# Generated by Django 3.2.25 on 2024-05-22 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(upload_to='productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avif'])]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(upload_to='productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avif'])]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avif'])]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, upload_to='productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avif'])]),
        ),
    ]
