# Generated by Django 3.2.25 on 2024-06-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
