# Generated by Django 3.2.25 on 2024-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20240522_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='productos.Categoria'),
        ),
    ]
