# Generated by Django 3.2.25 on 2024-05-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_subnombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='subnombre',
        ),
    ]
